[pytest]
filterwarnings =
    ignore::UserWarning:pydantic._internal._fields
    ignore::PendingDeprecationWarning:starlette.formparsers
    ignore:.*numpy.core.*
    ignore:.*Dependency.*:DeprecationWarning
    ignore:.*Using.*httpx.*with.*starlette.*:DeprecationWarning
